name: Dynamic Workflow
on:
  workflow_dispatch:

jobs:
  changes:
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            proj1: proj1/**
            proj2: proj2/**

  dynamic-changes:
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
            changed: 'proj*/**'
      - id: changes
        env:
          changed: ${{steps.filter.outputs.changed_files}}
        run: | 
          changes="$(echo $changed | jq -r '.[]' | cut -d'/' -f1 | sort | uniq)"
          echo "changes=${changes}" >> $GITHUB_OUTPUT
          

  build:
    needs: changes
    if: needs.changes.outputs.projects != '[]'
    strategy:
      matrix:
        project: ${{ fromJSON(needs.changes.outputs.projects) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building ${{ matrix.project }}"
      - run: make
        working-directory: ${{ matrix.project }}
